// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqXjfj4qdoJkBUEPIPuN-rGlHAdLegCbE',
    appId: '1:949823634763:web:e017d081b05595f5227cce',
    messagingSenderId: '949823634763',
    projectId: 'planeta-fitness-f',
    authDomain: 'planeta-fitness-f.firebaseapp.com',
    storageBucket: 'planeta-fitness-f.appspot.com',
    measurementId: 'G-NCD6J6HWLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh6K5g6NEhlA-94Qu2hWq_uVhXZvX9VtE',
    appId: '1:949823634763:android:4034672e70a2ff85227cce',
    messagingSenderId: '949823634763',
    projectId: 'planeta-fitness-f',
    storageBucket: 'planeta-fitness-f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzab6rd2yLxkEKzGmNZw8MBf4jSF4nfis',
    appId: '1:949823634763:ios:f3fbedadfc9d2c83227cce',
    messagingSenderId: '949823634763',
    projectId: 'planeta-fitness-f',
    storageBucket: 'planeta-fitness-f.appspot.com',
    iosBundleId: 'com.albadevs.gymFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzab6rd2yLxkEKzGmNZw8MBf4jSF4nfis',
    appId: '1:949823634763:ios:ba21970772627d3c227cce',
    messagingSenderId: '949823634763',
    projectId: 'planeta-fitness-f',
    storageBucket: 'planeta-fitness-f.appspot.com',
    iosBundleId: 'com.albadevs.gymFront.RunnerTests',
  );
}
